# CHANGEME: Set these variable to your liking
title: ESPHome Remote Server Manager
description: With this ESPHome configuration you will be able to access the BIOS and terminal of the computer connected via UART over a serial TCP stream. At the same time basic things can be controlled and monitored remotely.
theme: jekyll-theme-slate
