external_components:
  source:
    type: git
    url: https://github.com/oxan/esphome-stream-server
    ref: master

stream_server:
  uart_id: uart_odroid
  port: 6638
  buffer_size: 128 # bytes

sensor:
  - platform: stream_server
    connection_count:
      name: Stream server number of connections

binary_sensor:
  - platform: stream_server
    connected:
      name: Stream server connected
